/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpgr32;

import java.awt.Image;
import java.io.File;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nico
 */
public class ActualizarServicioInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarServicioInternalFrame
     */
    private IControladorPublicacion cp;
    private Image im1;
    private Image im2;
    private Image im3;
    private DataServicio ds;
    private boolean destino;
    private boolean modim1;
    private boolean modim2;
    private boolean modim3;
    public ActualizarServicioInternalFrame() {
        initComponents();
        im1 = null;
        im2 = null;
        im3 = null;
        destino = false;
        
        PrimerPanel.setVisible(true);
        SegundoPanel.setVisible(false);
        cp = FabricaControladores.getInstancia().getControladorPublicacion();
        Set<DataServicio> servicios = cp.listarServicios();
        DefaultTableModel tm = (DefaultTableModel) TablaPrimerPanel.getModel();
        while(TablaPrimerPanel.getRowCount() > 0)
           tm.removeRow(0);
        for (DataServicio s : servicios)
           tm.addRow(new Object[]{s.getProveedor(), s.getNombre(), Float.toString(s.getPrecio())});
        TablaPrimerPanel.setModel(tm);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        PrimerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPrimerPanel = new javax.swing.JTable();
        TituloPrimerPanel = new javax.swing.JLabel();
        SiguientePrimerPanel = new javax.swing.JButton();
        SegundoPanel = new javax.swing.JPanel();
        NombreServicioSegundoPanel = new javax.swing.JLabel();
        ProveedorSegundoPanel = new javax.swing.JLabel();
        DescripcionLabelSegundoPanel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescripcionSegundoPanel = new javax.swing.JTextArea();
        PrimeraImagenSegundoPanel = new javax.swing.JLabel();
        SegundaImagenSegundoPanel = new javax.swing.JLabel();
        TercerImagenSegundoPanel = new javax.swing.JLabel();
        PrecioLabelSegundoPanel = new javax.swing.JLabel();
        PrecioSegundoPanel = new javax.swing.JTextField();
        ActualizarSegundoPanel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SegundoPanelPaisOrigen = new javax.swing.JComboBox<String>();
        SegundoPanelCiudadOrigen = new javax.swing.JComboBox<String>();
        SegundoPanelDestino = new javax.swing.JCheckBox();
        SegundoPanelPaisDestino = new javax.swing.JComboBox<String>();
        SegundoPanelCiudadDestino = new javax.swing.JComboBox<String>();

        getContentPane().setLayout(new java.awt.CardLayout());

        TablaPrimerPanel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proveedor", "Nombre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPrimerPanel.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaPrimerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPrimerPanelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPrimerPanel);

        TituloPrimerPanel.setText("Actualizar Servicio");

        SiguientePrimerPanel.setText("Siguiente");
        SiguientePrimerPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguientePrimerPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PrimerPanelLayout = new javax.swing.GroupLayout(PrimerPanel);
        PrimerPanel.setLayout(PrimerPanelLayout);
        PrimerPanelLayout.setHorizontalGroup(
            PrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrimerPanelLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(TituloPrimerPanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrimerPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(PrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SiguientePrimerPanel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        PrimerPanelLayout.setVerticalGroup(
            PrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrimerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloPrimerPanel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(SiguientePrimerPanel)
                .addGap(20, 20, 20))
        );

        getContentPane().add(PrimerPanel, "card2");

        NombreServicioSegundoPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreServicioSegundoPanel.setText("Nombre servicio");
        NombreServicioSegundoPanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ProveedorSegundoPanel.setText("Proveedor: mHooch");

        DescripcionLabelSegundoPanel.setText("Descripción:");

        DescripcionSegundoPanel.setColumns(20);
        DescripcionSegundoPanel.setRows(5);
        jScrollPane2.setViewportView(DescripcionSegundoPanel);

        PrimeraImagenSegundoPanel.setForeground(new java.awt.Color(153, 153, 153));
        PrimeraImagenSegundoPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PrimeraImagenSegundoPanel.setText("[Doble click]");
        PrimeraImagenSegundoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PrimeraImagenSegundoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrimeraImagenSegundoPanelMouseClicked(evt);
            }
        });

        SegundaImagenSegundoPanel.setForeground(new java.awt.Color(153, 153, 153));
        SegundaImagenSegundoPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SegundaImagenSegundoPanel.setText("[Doble click]");
        SegundaImagenSegundoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SegundaImagenSegundoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SegundaImagenSegundoPanelMouseClicked(evt);
            }
        });

        TercerImagenSegundoPanel.setForeground(new java.awt.Color(153, 153, 153));
        TercerImagenSegundoPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TercerImagenSegundoPanel.setText("[Doble click]");
        TercerImagenSegundoPanel.setToolTipText("");
        TercerImagenSegundoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TercerImagenSegundoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TercerImagenSegundoPanelMouseClicked(evt);
            }
        });

        PrecioLabelSegundoPanel.setText("Precio (USD):");

        PrecioSegundoPanel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PrecioSegundoPanel.setText("1000");

        ActualizarSegundoPanel.setText("Actualizar");
        ActualizarSegundoPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarSegundoPanelActionPerformed(evt);
            }
        });

        jLabel1.setText("Origen:");

        SegundoPanelPaisOrigen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SegundoPanelPaisOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoPanelPaisOrigenActionPerformed(evt);
            }
        });

        SegundoPanelCiudadOrigen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SegundoPanelDestino.setText("Destino");

        SegundoPanelPaisDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SegundoPanelPaisDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoPanelPaisDestinoActionPerformed(evt);
            }
        });

        SegundoPanelCiudadDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout SegundoPanelLayout = new javax.swing.GroupLayout(SegundoPanel);
        SegundoPanel.setLayout(SegundoPanelLayout);
        SegundoPanelLayout.setHorizontalGroup(
            SegundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SegundoPanelLayout.createSequentialGroup()
                .addGroup(SegundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SegundoPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ActualizarSegundoPanel))
                    .addGroup(SegundoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SegundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SegundoPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(SegundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(SegundoPanelLayout.createSequentialGroup()
                                        .addComponent(PrecioLabelSegundoPanel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PrecioSegundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(PrimeraImagenSegundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(SegundaImagenSegundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(TercerImagenSegundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(SegundoPanelLayout.createSequentialGroup()
                                .addGroup(SegundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SegundoPanelCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SegundoPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(151, 151, 151)
                                        .addComponent(SegundoPanelCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(SegundoPanelLayout.createSequentialGroup()
                        .addGroup(SegundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SegundoPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ProveedorSegundoPanel))
                            .addGroup(SegundoPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(NombreServicioSegundoPanel))
                            .addGroup(SegundoPanelLayout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(DescripcionLabelSegundoPanel))
                            .addGroup(SegundoPanelLayout.createSequentialGroup()
                                .addComponent(SegundoPanelDestino)
                                .addGroup(SegundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SegundoPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(SegundoPanelPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SegundoPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(SegundoPanelPaisDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SegundoPanelLayout.setVerticalGroup(
            SegundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SegundoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreServicioSegundoPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProveedorSegundoPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescripcionLabelSegundoPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(SegundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrimeraImagenSegundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SegundaImagenSegundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TercerImagenSegundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(SegundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioLabelSegundoPanel)
                    .addComponent(PrecioSegundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(SegundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SegundoPanelPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SegundoPanelCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(SegundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SegundoPanelCiudadDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SegundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SegundoPanelDestino)
                        .addComponent(SegundoPanelPaisDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(ActualizarSegundoPanel)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(SegundoPanel, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SiguientePrimerPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguientePrimerPanelActionPerformed
        try{
            if (TablaPrimerPanel.getSelectedRow() == -1)
                JOptionPane.showMessageDialog(null, "Debes seleccionar un servicio", "Warning", JOptionPane.WARNING_MESSAGE);
            else
            {
                ds = cp.infoServicio((String)TablaPrimerPanel.getValueAt(TablaPrimerPanel.getSelectedRow(), 0), (String)TablaPrimerPanel.getValueAt(TablaPrimerPanel.getSelectedRow(), 1));
                cp.seleccionarServicio((String)TablaPrimerPanel.getValueAt(TablaPrimerPanel.getSelectedRow(), 0), ds.getNombre());
                StringBuilder sb = new StringBuilder();
                sb.append("Nombre: ");
                sb.append(ds.getNombre());
                NombreServicioSegundoPanel.setText(sb.toString());
                sb = new StringBuilder();
                sb.append("Proveedor: ");
                sb.append(ds.getProveedor());
                ProveedorSegundoPanel.setText(sb.toString());
                DescripcionSegundoPanel.setText(ds.getDescripcion());
                PrecioSegundoPanel.setText(Float.toString(ds.getPrecio()));
                Set<Image> imagenes = ds.getImagenes();
                if (!(imagenes.isEmpty()))
                {
                    Iterator<Image> it = imagenes.iterator();
                    im1 = it.next();
                    PrimeraImagenSegundoPanel.setIcon(new ImageIcon(im1.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
                    if (it.hasNext())
                    {
                        im2 = it.next();
                        SegundaImagenSegundoPanel.setIcon(new ImageIcon(im2.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
                        if (it.hasNext())
                        {
                            im3 = it.next();
                            SegundaImagenSegundoPanel.setIcon(new ImageIcon(im3.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));            
                        }
                    }

                }
                //origen
                DefaultComboBoxModel<String> dc = (DefaultComboBoxModel<String>) SegundoPanelPaisOrigen.getModel();
                dc.removeAllElements();
                Set<String> paises = cp.listarPaises();
                for (String pais : paises)
                    dc.addElement(pais);
                SegundoPanelPaisOrigen.setSelectedItem(ds.getPaisOrigen());
                if (ds.getPaisDestino().compareTo("No tiene")== 0)
                {
                    destino = false;
                    SegundoPanelDestino.setSelected(false);
                    SegundoPanelPaisDestino.setVisible(false);
                    SegundoPanelCiudadDestino.setVisible(false);
                }
                else
                {
                    destino = true;
                    SegundoPanelDestino.setSelected(true);
                    SegundoPanelPaisDestino.setVisible(true);
                    SegundoPanelCiudadDestino.setVisible(true);
                    dc = (DefaultComboBoxModel<String>) SegundoPanelPaisDestino.getModel();
                    dc.removeAllElements();
                    for (String pais : paises)
                        dc.addElement(pais);
                    SegundoPanelPaisDestino.setSelectedItem(ds.getPaisDestino());
                }
                PrimerPanel.setVisible(false);
                SegundoPanel.setVisible(true);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"ERROR", JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_SiguientePrimerPanelActionPerformed

    private void TablaPrimerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPrimerPanelMouseClicked
        if(evt.getClickCount() == 2)
            SiguientePrimerPanel.doClick();
    }//GEN-LAST:event_TablaPrimerPanelMouseClicked

    private void PrimeraImagenSegundoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrimeraImagenSegundoPanelMouseClicked
        if (evt.getClickCount() == 2)
        {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de imagen","jpg");
            jFileChooser1.setFileFilter(filter);
            jFileChooser1.setVisible(true);
            int opcion = jFileChooser1.showOpenDialog(null);
            if (opcion == JFileChooser.APPROVE_OPTION)
            {
                String arch = jFileChooser1.getSelectedFile().getPath();
                PrimeraImagenSegundoPanel.setIcon(new ImageIcon(arch));
                ImageIcon icon = new ImageIcon(arch);
                im1 = icon.getImage();
                //Se modifica el tamaño de la imagen
                Image imgmod = im1.getScaledInstance(100,100,java.awt.Image.SCALE_SMOOTH);
                //Se genera el ImageIcon con la nueva imagen
                ImageIcon nuevoIcono = new ImageIcon(imgmod);
                PrimeraImagenSegundoPanel.setIcon(nuevoIcono);
                PrimeraImagenSegundoPanel.setSize(100,100);
                //PrimeraImagenSegundoPanel.setText(null);
            }
        }
    }//GEN-LAST:event_PrimeraImagenSegundoPanelMouseClicked

    private void SegundaImagenSegundoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SegundaImagenSegundoPanelMouseClicked
        if (evt.getClickCount() == 2)
        {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de imagen","jpg");
            jFileChooser1.setFileFilter(filter);
            jFileChooser1.setVisible(true);
            int opcion = jFileChooser1.showOpenDialog(null);
            if (opcion == JFileChooser.APPROVE_OPTION)
            {
                String arch = jFileChooser1.getSelectedFile().getPath();
                SegundaImagenSegundoPanel.setIcon(new ImageIcon(arch));
                ImageIcon icon = new ImageIcon(arch);
                im2 = icon.getImage();
                //Se modifica el tamaño de la imagen
                Image imgmod = im2.getScaledInstance(100,100,java.awt.Image.SCALE_SMOOTH);
                //Se genera el ImageIcon con la nueva imagen
                ImageIcon nuevoIcono = new ImageIcon(imgmod);
                SegundaImagenSegundoPanel.setIcon(nuevoIcono);
                SegundaImagenSegundoPanel.setSize(100,100);
                //SegundaImagenSegundoPanel.setText(null);
            }
        }
    }//GEN-LAST:event_SegundaImagenSegundoPanelMouseClicked

    private void TercerImagenSegundoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TercerImagenSegundoPanelMouseClicked
        if (evt.getClickCount() == 2)
        {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de imagen","jpg");
            jFileChooser1.setFileFilter(filter);
            jFileChooser1.setVisible(true);
            int opcion = jFileChooser1.showOpenDialog(null);
            if (opcion == JFileChooser.APPROVE_OPTION)
            {
                String arch = jFileChooser1.getSelectedFile().getPath();
                TercerImagenSegundoPanel.setIcon(new ImageIcon(arch));
                ImageIcon icon = new ImageIcon(arch);
                im3 = icon.getImage();
                //Se modifica el tamaño de la imagen
                Image imgmod = im3.getScaledInstance(100,100,java.awt.Image.SCALE_SMOOTH);
                //Se genera el ImageIcon con la nueva imagen
                ImageIcon nuevoIcono = new ImageIcon(imgmod);
                TercerImagenSegundoPanel.setIcon(nuevoIcono);
                TercerImagenSegundoPanel.setSize(100,100);
                //TercerImagenSegundoPanel.setText(null);
            }
        }
    }//GEN-LAST:event_TercerImagenSegundoPanelMouseClicked

    private void ActualizarSegundoPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarSegundoPanelActionPerformed
        try{
            if (!(ds.getDescripcion().compareTo(DescripcionSegundoPanel.getText()) == 0))
                cp.modificarDescripcionServicio(DescripcionSegundoPanel.getText());
            if(!(ds.getPrecio() == Float.parseFloat(PrecioSegundoPanel.getText())))
                cp.modificarPrecioServicio(Float.parseFloat(PrecioSegundoPanel.getText()));
            if((!(ds.getPaisOrigen().compareTo((String)SegundoPanelPaisOrigen.getSelectedItem())==0)) || (!(ds.getCiudadOrigen().compareTo((String)SegundoPanelCiudadOrigen.getSelectedItem())==0)))
                cp.modificarOrigenServicio((String)SegundoPanelPaisOrigen.getSelectedItem(), (String)SegundoPanelCiudadOrigen.getSelectedItem());
            if((destino) || (SegundoPanelDestino.isSelected()))
            {
                if (SegundoPanelDestino.isSelected())
                        cp.modificarDestinoServicio((String)SegundoPanelPaisDestino.getSelectedItem(), (String)SegundoPanelCiudadDestino.getSelectedItem());
                else
                    cp.eliminarDestinoServicio();
            }
            Set<Image> im = new HashSet<>();
            if(im1 != null)
                im.add(im1);
            if(im2 != null)
                im.add(im2);
            if(im3 != null)
                im.add(im3);
            cp.modificarImagenesServicio(im);
            JOptionPane.showMessageDialog(null, "El servicio se actualizo con exito");
            SwingUtilities.getWindowAncestor(this).repaint();
            SwingUtilities.getWindowAncestor(this).revalidate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_ActualizarSegundoPanelActionPerformed

    private void SegundoPanelPaisOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoPanelPaisOrigenActionPerformed
        DefaultComboBoxModel<String> dm = (DefaultComboBoxModel<String>) SegundoPanelCiudadOrigen.getModel();
        dm.removeAllElements();
        if (!(SegundoPanelPaisOrigen.getSelectedItem() == null))
        {
            Set<String> cities = cp.listarCiudades(((String)SegundoPanelPaisOrigen.getSelectedItem()));
            for (String c : cities)
                dm.addElement(c);
        }
       
    }//GEN-LAST:event_SegundoPanelPaisOrigenActionPerformed

    private void SegundoPanelPaisDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoPanelPaisDestinoActionPerformed
        DefaultComboBoxModel<String> dm = (DefaultComboBoxModel<String>) SegundoPanelCiudadDestino.getModel();
        dm.removeAllElements();
        if (!(SegundoPanelPaisDestino.getSelectedItem() == null))
        {
            Set<String> cities = cp.listarCiudades(((String)SegundoPanelPaisDestino.getSelectedItem()));
            for (String c : cities)
                dm.addElement(c);
        }
    }//GEN-LAST:event_SegundoPanelPaisDestinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarSegundoPanel;
    private javax.swing.JLabel DescripcionLabelSegundoPanel;
    private javax.swing.JTextArea DescripcionSegundoPanel;
    private javax.swing.JLabel NombreServicioSegundoPanel;
    private javax.swing.JLabel PrecioLabelSegundoPanel;
    private javax.swing.JTextField PrecioSegundoPanel;
    private javax.swing.JPanel PrimerPanel;
    private javax.swing.JLabel PrimeraImagenSegundoPanel;
    private javax.swing.JLabel ProveedorSegundoPanel;
    private javax.swing.JLabel SegundaImagenSegundoPanel;
    private javax.swing.JPanel SegundoPanel;
    private javax.swing.JComboBox<String> SegundoPanelCiudadDestino;
    private javax.swing.JComboBox<String> SegundoPanelCiudadOrigen;
    private javax.swing.JCheckBox SegundoPanelDestino;
    private javax.swing.JComboBox<String> SegundoPanelPaisDestino;
    private javax.swing.JComboBox<String> SegundoPanelPaisOrigen;
    private javax.swing.JButton SiguientePrimerPanel;
    private javax.swing.JTable TablaPrimerPanel;
    private javax.swing.JLabel TercerImagenSegundoPanel;
    private javax.swing.JLabel TituloPrimerPanel;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
