/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpgr32;

import java.util.*;
import java.text.*;
import java.util.Locale;
import javax.swing.DefaultListModel;

/**
 *
 * @author Nicolás Rostán
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
	initComponents();
	setLocationRelativeTo(null); //Centra el MainFrame en la pantalla
	PanelCentral.removeAll();
	PanelCentral.repaint();
	PanelCentral.revalidate(); //HACE QUE NO SE VEA NADA AL ABRIR EL PROGRAMA
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClienteOProveedor = new javax.swing.ButtonGroup();
        PanelCentral = new javax.swing.JPanel();
        RegistrarUsuarioFrame = new javax.swing.JInternalFrame();
        RegUsuarioLabel = new javax.swing.JLabel();
        RegUsuarioNicknameLabel = new javax.swing.JLabel();
        RegUsuarioNombreLabel = new javax.swing.JLabel();
        RegUsuarioApellidoLabel = new javax.swing.JLabel();
        RegUsuarioCorreoLabel = new javax.swing.JLabel();
        RegUsuarioFechaLabel = new javax.swing.JLabel();
        RegUsuarioSeleccionarImagenButton = new javax.swing.JButton();
        RegUsuarioNicknameTextField = new javax.swing.JTextField();
        RegUsuarioNombreTextField = new javax.swing.JTextField();
        RegUsuarioApellidoTextField = new javax.swing.JTextField();
        RegUsuarioCorreoTextField = new javax.swing.JTextField();
        RegUsuarioDiaComboBox = new javax.swing.JComboBox<Integer>();
        RegUsuarioMesComboBox = new javax.swing.JComboBox<Integer>();
        RegUsuarioAnioComboBox = new javax.swing.JComboBox<Integer>();
        RegUsuarioClienteRadioButton = new javax.swing.JRadioButton();
        RegUsuarioProveedorRadioButton = new javax.swing.JRadioButton();
        RegUsuarioNombreEmpresaLabel = new javax.swing.JLabel();
        RegUsuarioURLLabel = new javax.swing.JLabel();
        RegUsuarioNombreEmpresaTextField = new javax.swing.JTextField();
        RegUsuarioURLTextField = new javax.swing.JTextField();
        RegUsuarioAceptar = new javax.swing.JButton();
        RegUsuarioCancelar = new javax.swing.JButton();
        RegUsuarioErrorLabel = new javax.swing.JLabel();
        ConsultaUsuarioFrame = new javax.swing.JInternalFrame();
        ConsultaUsuarioVerInfoLabel = new javax.swing.JLabel();
        ConsultaUsuarioNicknameLabel = new javax.swing.JLabel();
        ConsultaUsuarioTextFieldLabel = new javax.swing.JTextField();
        ConsultaUsuarioApellidoNombreLabel = new javax.swing.JLabel();
        ConsultaUsuarioTipoLabel = new javax.swing.JLabel();
        ConsultaUsuarioNickLabel = new javax.swing.JLabel();
        ConsultaUsuarioCorreoLabel = new javax.swing.JLabel();
        ConsultaUsuarioFechaLabel = new javax.swing.JLabel();
        ConsultaUsuarioEmpresaLabel = new javax.swing.JLabel();
        ConsultaUsuarioURLLabel = new javax.swing.JLabel();
        ConsultaUsuarioImagePanel = new javax.swing.JPanel();
        ConsultaUsuarioNoImgLabel = new javax.swing.JLabel();
        ConsultaUsuarioBuscarButton = new javax.swing.JButton();
        ConsultaUsuarioNicknameLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaClientes = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        BarraMenu = new javax.swing.JMenuBar();
        MenuInicio = new javax.swing.JMenu();
        MenuRegistros = new javax.swing.JMenu();
        MenuRegistrarUsuario = new javax.swing.JMenuItem();
        MenuConsultas = new javax.swing.JMenu();
        infoCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tarea 1");
        setPreferredSize(new java.awt.Dimension(450, 550));
        setResizable(false);

        PanelCentral.setLayout(new java.awt.CardLayout());

        RegistrarUsuarioFrame.setVisible(false);
        RegistrarUsuarioFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegUsuarioLabel.setText("Registrar Usuario");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 11, -1, -1));

        RegUsuarioNicknameLabel.setText("Nickname:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioNicknameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, -1));

        RegUsuarioNombreLabel.setText("Nombre:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioNombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        RegUsuarioApellidoLabel.setText("Apellido:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioApellidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        RegUsuarioCorreoLabel.setText("Correo:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioCorreoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, -1, -1));

        RegUsuarioFechaLabel.setText("Fecha de Nacimiento:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioFechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, -1, -1));

        RegUsuarioSeleccionarImagenButton.setText("Seleccionar Imagen");
        RegUsuarioSeleccionarImagenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegUsuarioSeleccionarImagenButtonActionPerformed(evt);
            }
        });
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioSeleccionarImagenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 198, -1, -1));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioNicknameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 190, -1));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioNombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 190, -1));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioApellidoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 190, -1));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioCorreoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 190, -1));

        RegUsuarioDiaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        RegUsuarioDiaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegUsuarioDiaComboBoxActionPerformed(evt);
            }
        });
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioDiaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        RegUsuarioMesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioMesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        RegUsuarioAnioComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015" }));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioAnioComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 80, -1));

        RegUsuarioClienteRadioButton.setSelected(true);
        RegUsuarioClienteRadioButton.setText("Cliente");
        RegUsuarioClienteRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegUsuarioClienteRadioButtonActionPerformed(evt);
            }
        });
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioClienteRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 198, -1, -1));

        RegUsuarioProveedorRadioButton.setText("Proveedor");
        RegUsuarioProveedorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegUsuarioProveedorRadioButtonActionPerformed(evt);
            }
        });
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioProveedorRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 198, -1, -1));

        RegUsuarioNombreEmpresaLabel.setText("Nombre Empresa:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioNombreEmpresaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 239, -1, -1));

        RegUsuarioURLLabel.setText("URL:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioURLLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 267, -1, -1));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioNombreEmpresaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 190, -1));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioURLTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 190, -1));

        RegUsuarioAceptar.setText("Aceptar");
        RegUsuarioAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegUsuarioAceptarActionPerformed(evt);
            }
        });
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        RegUsuarioCancelar.setText("Cancelar");
        RegUsuarioCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegUsuarioCancelarActionPerformed(evt);
            }
        });
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        RegUsuarioErrorLabel.setForeground(new java.awt.Color(204, 0, 0));
        RegUsuarioErrorLabel.setText("LABEL PARA INDICIAR ERRORES");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 302, -1, -1));

        PanelCentral.add(RegistrarUsuarioFrame, "card2");

        ConsultaUsuarioFrame.setVisible(true);

        ConsultaUsuarioVerInfoLabel.setText("Ver Informacion de Usuario");

        ConsultaUsuarioNicknameLabel.setText("Clientes:");

        ConsultaUsuarioTextFieldLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaUsuarioTextFieldLabelActionPerformed(evt);
            }
        });

        ConsultaUsuarioApellidoNombreLabel.setText("Apellido, Nombre");

        ConsultaUsuarioTipoLabel.setText("Tipo: Proveedor");

        ConsultaUsuarioNickLabel.setText("Nickname: Nickname");

        ConsultaUsuarioCorreoLabel.setText("Correo: Correo");

        ConsultaUsuarioFechaLabel.setText("Fecha de Nacimiento: 10/10/1950");

        ConsultaUsuarioEmpresaLabel.setText("Empresa: Nombre Empresa");

        ConsultaUsuarioURLLabel.setText("URL: www.empresa.com");

        ConsultaUsuarioNoImgLabel.setText("No hay imagen disponible");

        javax.swing.GroupLayout ConsultaUsuarioImagePanelLayout = new javax.swing.GroupLayout(ConsultaUsuarioImagePanel);
        ConsultaUsuarioImagePanel.setLayout(ConsultaUsuarioImagePanelLayout);
        ConsultaUsuarioImagePanelLayout.setHorizontalGroup(
            ConsultaUsuarioImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaUsuarioImagePanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(ConsultaUsuarioNoImgLabel)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        ConsultaUsuarioImagePanelLayout.setVerticalGroup(
            ConsultaUsuarioImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaUsuarioImagePanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(ConsultaUsuarioNoImgLabel)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        ConsultaUsuarioBuscarButton.setText("Buscar");
        ConsultaUsuarioBuscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaUsuarioBuscarButtonActionPerformed(evt);
            }
        });

        ConsultaUsuarioNicknameLabel1.setText("Nickname:");

        ControladorUsuario contU = new ControladorUsuario();
        Set <DataUsuario> clientes = contU.listarClientes();
        for(DataUsuario c : clientes) {
            listaClientes.setName(c.getNombre());
        }
        jScrollPane1.setViewportView(listaClientes);

        jButton1.setText("Seleccionar Imagen");

        javax.swing.GroupLayout ConsultaUsuarioFrameLayout = new javax.swing.GroupLayout(ConsultaUsuarioFrame.getContentPane());
        ConsultaUsuarioFrame.getContentPane().setLayout(ConsultaUsuarioFrameLayout);
        ConsultaUsuarioFrameLayout.setHorizontalGroup(
            ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                .addGroup(ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(ConsultaUsuarioVerInfoLabel))
                        .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(ConsultaUsuarioNicknameLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(ConsultaUsuarioTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(ConsultaUsuarioBuscarButton))
                        .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ConsultaUsuarioEmpresaLabel)
                                .addComponent(ConsultaUsuarioURLLabel)
                                .addComponent(ConsultaUsuarioFechaLabel)
                                .addComponent(ConsultaUsuarioCorreoLabel)
                                .addComponent(ConsultaUsuarioNickLabel)
                                .addComponent(ConsultaUsuarioTipoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ConsultaUsuarioApellidoNombreLabel)
                                .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(jButton1)
                                    .addGap(44, 44, 44)
                                    .addComponent(ConsultaUsuarioImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ConsultaUsuarioFrameLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ConsultaUsuarioNicknameLabel)
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConsultaUsuarioFrameLayout.setVerticalGroup(
            ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConsultaUsuarioVerInfoLabel)
                .addGroup(ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConsultaUsuarioTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConsultaUsuarioBuscarButton)
                            .addComponent(ConsultaUsuarioNicknameLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaUsuarioApellidoNombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaUsuarioTipoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaUsuarioNickLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaUsuarioCorreoLabel)
                        .addGap(7, 7, 7)
                        .addComponent(ConsultaUsuarioFechaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaUsuarioEmpresaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaUsuarioURLLabel)
                        .addGroup(ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConsultaUsuarioImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jButton1))))
                    .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(ConsultaUsuarioNicknameLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCentral.add(ConsultaUsuarioFrame, "card3");

        MenuInicio.setText("Inicio");
        BarraMenu.add(MenuInicio);

        MenuRegistros.setText("Registros");

        MenuRegistrarUsuario.setText("Registrar Usuario");
        MenuRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarUsuarioActionPerformed(evt);
            }
        });
        MenuRegistros.add(MenuRegistrarUsuario);

        BarraMenu.add(MenuRegistros);

        MenuConsultas.setText("Consultas");

        infoCliente.setText("Ver Informacion de Cliente");
        infoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoClienteActionPerformed(evt);
            }
        });
        MenuConsultas.add(infoCliente);

        BarraMenu.add(MenuConsultas);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarUsuarioActionPerformed

	RegUsuarioAnioComboBox.removeAllItems();
	for (int i = 2015; i > 1900; i--) //genera los años
	    RegUsuarioAnioComboBox.addItem(i);
	ClienteOProveedor.add(RegUsuarioClienteRadioButton);
	ClienteOProveedor.add(RegUsuarioProveedorRadioButton);
	RegUsuarioNombreEmpresaLabel.setVisible(false);
	RegUsuarioURLLabel.setVisible(false);
	RegUsuarioErrorLabel.setVisible(false);
	RegUsuarioNombreEmpresaTextField.setVisible(false);
	RegUsuarioURLTextField.setVisible(false);
	PanelCentral.removeAll();
	PanelCentral.add(RegistrarUsuarioFrame);
	PanelCentral.repaint();
	PanelCentral.revalidate();
	//Muestra el frame de registrar usario en el panel central
    }//GEN-LAST:event_MenuRegistrarUsuarioActionPerformed

    private void RegUsuarioSeleccionarImagenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegUsuarioSeleccionarImagenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegUsuarioSeleccionarImagenButtonActionPerformed

    private void RegUsuarioDiaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegUsuarioDiaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegUsuarioDiaComboBoxActionPerformed

    private void RegUsuarioClienteRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegUsuarioClienteRadioButtonActionPerformed
        RegUsuarioNombreEmpresaLabel.setVisible(false);
	RegUsuarioURLLabel.setVisible(false);
	RegUsuarioNombreEmpresaTextField.setVisible(false);
	RegUsuarioURLTextField.setVisible(false);
    }//GEN-LAST:event_RegUsuarioClienteRadioButtonActionPerformed

    private void RegUsuarioProveedorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegUsuarioProveedorRadioButtonActionPerformed
        RegUsuarioNombreEmpresaLabel.setVisible(true);
	RegUsuarioURLLabel.setVisible(true);
	RegUsuarioNombreEmpresaTextField.setVisible(true);
	RegUsuarioURLTextField.setVisible(true);
    }//GEN-LAST:event_RegUsuarioProveedorRadioButtonActionPerformed

    private void RegUsuarioCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegUsuarioCancelarActionPerformed
        this.RegUsuarioCancelar.doClick();
    }//GEN-LAST:event_RegUsuarioCancelarActionPerformed

    private void ConsultaUsuarioTextFieldLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaUsuarioTextFieldLabelActionPerformed
	ConsultaUsuarioBuscarButton.doClick();
    }//GEN-LAST:event_ConsultaUsuarioTextFieldLabelActionPerformed

    private void infoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoClienteActionPerformed
        ConsultaUsuarioApellidoNombreLabel.setVisible(false);
	ConsultaUsuarioTipoLabel.setVisible(false);
	ConsultaUsuarioNickLabel.setVisible(false);
	ConsultaUsuarioCorreoLabel.setVisible(false);
	ConsultaUsuarioFechaLabel.setVisible(false);
	ConsultaUsuarioEmpresaLabel.setVisible(false);
	ConsultaUsuarioURLLabel.setVisible(false);
	ConsultaUsuarioImagePanel.setVisible(false);
	ConsultaUsuarioNoImgLabel.setVisible(false);
	PanelCentral.removeAll();
	PanelCentral.add(ConsultaUsuarioFrame);
	PanelCentral.repaint();
	PanelCentral.revalidate();
    }//GEN-LAST:event_infoClienteActionPerformed

    private void RegUsuarioAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegUsuarioAceptarActionPerformed
        try
	{
	    ControladorUsuario ctrlUsr = new ControladorUsuario();
	    Calendar cal = Calendar.getInstance();
	    cal.set(Calendar.YEAR, (Integer)(RegUsuarioAnioComboBox.getSelectedItem()));
	    cal.set(Calendar.MONTH, (Integer)(RegUsuarioMesComboBox.getSelectedItem()));
	    cal.set(Calendar.DAY_OF_MONTH, (Integer)(RegUsuarioDiaComboBox.getSelectedItem()));
	    Date d = cal.getTime();
	    if(RegUsuarioClienteRadioButton.isSelected())
	    {
                ctrlUsr.altaCliente(RegUsuarioNombreTextField.getText(), RegUsuarioApellidoTextField.getText(), RegUsuarioNicknameTextField.getText() , 
                        RegUsuarioCorreoTextField.getText(), d);
                
	    }
            this.RegistrarUsuarioFrame.setClosed(true);
            
	}catch(Exception ex)
	{
	    //Muestra el error
	}
    }//GEN-LAST:event_RegUsuarioAceptarActionPerformed

    private void ConsultaUsuarioBuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaUsuarioBuscarButtonActionPerformed
        
    }//GEN-LAST:event_ConsultaUsuarioBuscarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	}
	catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
        //</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Interfaz().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.ButtonGroup ClienteOProveedor;
    private javax.swing.JLabel ConsultaUsuarioApellidoNombreLabel;
    private javax.swing.JButton ConsultaUsuarioBuscarButton;
    private javax.swing.JLabel ConsultaUsuarioCorreoLabel;
    private javax.swing.JLabel ConsultaUsuarioEmpresaLabel;
    private javax.swing.JLabel ConsultaUsuarioFechaLabel;
    private javax.swing.JInternalFrame ConsultaUsuarioFrame;
    private javax.swing.JPanel ConsultaUsuarioImagePanel;
    private javax.swing.JLabel ConsultaUsuarioNickLabel;
    private javax.swing.JLabel ConsultaUsuarioNicknameLabel;
    private javax.swing.JLabel ConsultaUsuarioNicknameLabel1;
    private javax.swing.JLabel ConsultaUsuarioNoImgLabel;
    private javax.swing.JTextField ConsultaUsuarioTextFieldLabel;
    private javax.swing.JLabel ConsultaUsuarioTipoLabel;
    private javax.swing.JLabel ConsultaUsuarioURLLabel;
    private javax.swing.JLabel ConsultaUsuarioVerInfoLabel;
    private javax.swing.JMenu MenuConsultas;
    private javax.swing.JMenu MenuInicio;
    private javax.swing.JMenuItem MenuRegistrarUsuario;
    private javax.swing.JMenu MenuRegistros;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JButton RegUsuarioAceptar;
    private javax.swing.JComboBox<Integer> RegUsuarioAnioComboBox;
    private javax.swing.JLabel RegUsuarioApellidoLabel;
    private javax.swing.JTextField RegUsuarioApellidoTextField;
    private javax.swing.JButton RegUsuarioCancelar;
    private javax.swing.JRadioButton RegUsuarioClienteRadioButton;
    private javax.swing.JLabel RegUsuarioCorreoLabel;
    private javax.swing.JTextField RegUsuarioCorreoTextField;
    private javax.swing.JComboBox<Integer> RegUsuarioDiaComboBox;
    private javax.swing.JLabel RegUsuarioErrorLabel;
    private javax.swing.JLabel RegUsuarioFechaLabel;
    private javax.swing.JLabel RegUsuarioLabel;
    private javax.swing.JComboBox<Integer> RegUsuarioMesComboBox;
    private javax.swing.JLabel RegUsuarioNicknameLabel;
    private javax.swing.JTextField RegUsuarioNicknameTextField;
    private javax.swing.JLabel RegUsuarioNombreEmpresaLabel;
    private javax.swing.JTextField RegUsuarioNombreEmpresaTextField;
    private javax.swing.JLabel RegUsuarioNombreLabel;
    private javax.swing.JTextField RegUsuarioNombreTextField;
    private javax.swing.JRadioButton RegUsuarioProveedorRadioButton;
    private javax.swing.JButton RegUsuarioSeleccionarImagenButton;
    private javax.swing.JLabel RegUsuarioURLLabel;
    private javax.swing.JTextField RegUsuarioURLTextField;
    private javax.swing.JInternalFrame RegistrarUsuarioFrame;
    private javax.swing.JMenuItem infoCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaClientes;
    // End of variables declaration//GEN-END:variables
}
