/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpgr32;

import java.util.*;
import java.text.*;
import java.util.Locale;
import javax.swing.DefaultListModel;

/**
 *
 * @author Nicolás Rostán
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
	initComponents();
	setLocationRelativeTo(null); //Centra el MainFrame en la pantalla
	PanelCentral.removeAll();
	PanelCentral.repaint();
	PanelCentral.revalidate(); //HACE QUE NO SE VEA NADA AL ABRIR EL PROGRAMA
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClienteOProveedor = new javax.swing.ButtonGroup();
        ConPadreOSinPadre = new javax.swing.ButtonGroup();
        PanelCentral = new javax.swing.JPanel();
        RegistrarUsuarioFrame = new javax.swing.JInternalFrame();
        RegUsuarioLabel = new javax.swing.JLabel();
        RegUsuarioNicknameLabel = new javax.swing.JLabel();
        RegUsuarioNombreLabel = new javax.swing.JLabel();
        RegUsuarioApellidoLabel = new javax.swing.JLabel();
        RegUsuarioCorreoLabel = new javax.swing.JLabel();
        RegUsuarioFechaLabel = new javax.swing.JLabel();
        RegUsuarioSeleccionarImagenButton = new javax.swing.JButton();
        RegUsuarioNicknameTextField = new javax.swing.JTextField();
        RegUsuarioNombreTextField = new javax.swing.JTextField();
        RegUsuarioApellidoTextField = new javax.swing.JTextField();
        RegUsuarioCorreoTextField = new javax.swing.JTextField();
        RegUsuarioDiaComboBox = new javax.swing.JComboBox<Integer>();
        RegUsuarioMesComboBox = new javax.swing.JComboBox<Integer>();
        RegUsuarioAnioComboBox = new javax.swing.JComboBox<Integer>();
        RegUsuarioClienteRadioButton = new javax.swing.JRadioButton();
        RegUsuarioProveedorRadioButton = new javax.swing.JRadioButton();
        RegUsuarioNombreEmpresaLabel = new javax.swing.JLabel();
        RegUsuarioURLLabel = new javax.swing.JLabel();
        RegUsuarioNombreEmpresaTextField = new javax.swing.JTextField();
        RegUsuarioURLTextField = new javax.swing.JTextField();
        RegUsuarioAceptar = new javax.swing.JButton();
        RegUsuarioCancelar = new javax.swing.JButton();
        RegUsuarioErrorLabel = new javax.swing.JLabel();
        ConsultaUsuarioFrame = new javax.swing.JInternalFrame();
        ConsultaUsuarioVerInfoLabel = new javax.swing.JLabel();
        ConsultaUsuarioNicknameLabel = new javax.swing.JLabel();
        ConsultaUsuarioTextFieldLabel = new javax.swing.JTextField();
        ConsultaUsuarioApellidoNombreLabel = new javax.swing.JLabel();
        ConsultaUsuarioTipoLabel = new javax.swing.JLabel();
        ConsultaUsuarioNickLabel = new javax.swing.JLabel();
        ConsultaUsuarioCorreoLabel = new javax.swing.JLabel();
        ConsultaUsuarioFechaLabel = new javax.swing.JLabel();
        ConsultaUsuarioEmpresaLabel = new javax.swing.JLabel();
        ConsultaUsuarioURLLabel = new javax.swing.JLabel();
        ConsultaUsuarioImagePanel = new javax.swing.JPanel();
        ConsultaUsuarioNoImgLabel = new javax.swing.JLabel();
        ConsultaUsuarioBuscarButton = new javax.swing.JButton();
        ConsultaUsuarioNicknameLabel1 = new javax.swing.JLabel();
        ConsultaUsuarioScrollPane = new javax.swing.JScrollPane();
        ConsultaUsuarioListaClientes = new javax.swing.JList();
        ConsultaUsuarioSelecImagenButton = new javax.swing.JButton();
        RegistrarCategoriaFrame = new javax.swing.JInternalFrame();
        RegCategoriaLabel = new javax.swing.JLabel();
        RegCategoriaNomCategoriaLabel = new javax.swing.JLabel();
        RegCategoriaNombreCategoriaTextField = new javax.swing.JTextField();
        RegCategoriaCategoriaPadreLabel = new javax.swing.JLabel();
        RegCategoriaSinPadreRadioButton = new javax.swing.JRadioButton();
        RegCategoriaConPadreRadioButton = new javax.swing.JRadioButton();
        RegCategoriaSelecCategoriaPadreLabel = new javax.swing.JLabel();
        RegCategoriaListarCategoriasScrollPane = new javax.swing.JScrollPane();
        RegCategoriaListarCategoriasTree = new javax.swing.JTree();
        RegCategoriaAceptarButton = new javax.swing.JButton();
        RegCategoriaCancelarButton = new javax.swing.JButton();
        RegistrarServicioFrame = new javax.swing.JInternalFrame();
        RegistrarServicioLabel = new javax.swing.JLabel();
        RegistrarServicioNomServicioLabel = new javax.swing.JLabel();
        RegistrarServicioNomServicioTextField = new javax.swing.JTextField();
        RegistrarServicioDescripcionLabel = new javax.swing.JLabel();
        RegistrarServicioTextField = new javax.swing.JTextField();
        RegistrarServicioSelecImagenesButton = new javax.swing.JButton();
        RegistrarServicioMax3ImagLabel = new javax.swing.JLabel();
        RegistrarServcioPrecioLabel = new javax.swing.JLabel();
        RegistrarServicioPrecioTextField = new javax.swing.JTextField();
        RegistrarServicioCiudadOrigenLabel = new javax.swing.JLabel();
        RegistrarServicioCiudadDestinoLabel = new javax.swing.JLabel();
        RegistrarServicioConjCategoriasLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RegistrarServicioCategoriasList = new javax.swing.JList();
        RegistrarServicioProveedorLabel = new javax.swing.JLabel();
        RegistrarServicioAceptarButton = new javax.swing.JButton();
        RegistrarServicioCancelarButton = new javax.swing.JButton();
        RegistrarServicioProveedorComboBox = new javax.swing.JComboBox();
        RegistrarServicioCiudadDestinoComboBox = new javax.swing.JComboBox();
        RegistrarServicioCiudadOrigenComboBox = new javax.swing.JComboBox();
        BarraMenu = new javax.swing.JMenuBar();
        MenuInicio = new javax.swing.JMenu();
        MenuRegistros = new javax.swing.JMenu();
        MenuRegistrarUsuario = new javax.swing.JMenuItem();
        MenuRegistrarCategoria = new javax.swing.JMenuItem();
        MenuRegistrarServicio = new javax.swing.JMenuItem();
        MenuConsultas = new javax.swing.JMenu();
        infoCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tarea 1");
        setPreferredSize(new java.awt.Dimension(450, 550));
        setResizable(false);

        PanelCentral.setLayout(new java.awt.CardLayout());

        RegistrarUsuarioFrame.setVisible(false);
        RegistrarUsuarioFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegUsuarioLabel.setText("Registrar Usuario");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 11, -1, -1));

        RegUsuarioNicknameLabel.setText("Nickname:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioNicknameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, -1));

        RegUsuarioNombreLabel.setText("Nombre:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioNombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        RegUsuarioApellidoLabel.setText("Apellido:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioApellidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        RegUsuarioCorreoLabel.setText("Correo:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioCorreoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, -1, -1));

        RegUsuarioFechaLabel.setText("Fecha de Nacimiento:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioFechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, -1, -1));

        RegUsuarioSeleccionarImagenButton.setText("Seleccionar Imagen");
        RegUsuarioSeleccionarImagenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegUsuarioSeleccionarImagenButtonActionPerformed(evt);
            }
        });
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioSeleccionarImagenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 198, -1, -1));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioNicknameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 190, -1));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioNombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 190, -1));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioApellidoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 190, -1));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioCorreoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 190, -1));

        RegUsuarioDiaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        RegUsuarioDiaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegUsuarioDiaComboBoxActionPerformed(evt);
            }
        });
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioDiaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        RegUsuarioMesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioMesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        RegUsuarioAnioComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015" }));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioAnioComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 80, -1));

        RegUsuarioClienteRadioButton.setSelected(true);
        RegUsuarioClienteRadioButton.setText("Cliente");
        RegUsuarioClienteRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegUsuarioClienteRadioButtonActionPerformed(evt);
            }
        });
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioClienteRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 198, -1, -1));

        RegUsuarioProveedorRadioButton.setText("Proveedor");
        RegUsuarioProveedorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegUsuarioProveedorRadioButtonActionPerformed(evt);
            }
        });
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioProveedorRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 198, -1, -1));

        RegUsuarioNombreEmpresaLabel.setText("Nombre Empresa:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioNombreEmpresaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 239, -1, -1));

        RegUsuarioURLLabel.setText("URL:");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioURLLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 267, -1, -1));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioNombreEmpresaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 190, -1));
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioURLTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 190, -1));

        RegUsuarioAceptar.setText("Aceptar");
        RegUsuarioAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegUsuarioAceptarActionPerformed(evt);
            }
        });
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        RegUsuarioCancelar.setText("Cancelar");
        RegUsuarioCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegUsuarioCancelarActionPerformed(evt);
            }
        });
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        RegUsuarioErrorLabel.setForeground(new java.awt.Color(204, 0, 0));
        RegUsuarioErrorLabel.setText("LABEL PARA INDICIAR ERRORES");
        RegistrarUsuarioFrame.getContentPane().add(RegUsuarioErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 302, -1, -1));

        PanelCentral.add(RegistrarUsuarioFrame, "card2");

        ConsultaUsuarioFrame.setVisible(true);

        ConsultaUsuarioVerInfoLabel.setText("Ver Informacion de Usuario");

        ConsultaUsuarioNicknameLabel.setText("Clientes:");

        ConsultaUsuarioTextFieldLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaUsuarioTextFieldLabelActionPerformed(evt);
            }
        });

        ConsultaUsuarioApellidoNombreLabel.setText("Apellido, Nombre");

        ConsultaUsuarioTipoLabel.setText("Tipo: Proveedor");

        ConsultaUsuarioNickLabel.setText("Nickname: Nickname");

        ConsultaUsuarioCorreoLabel.setText("Correo: Correo");

        ConsultaUsuarioFechaLabel.setText("Fecha de Nacimiento: 10/10/1950");

        ConsultaUsuarioEmpresaLabel.setText("Empresa: Nombre Empresa");

        ConsultaUsuarioURLLabel.setText("URL: www.empresa.com");

        ConsultaUsuarioNoImgLabel.setText("No hay imagen disponible");

        javax.swing.GroupLayout ConsultaUsuarioImagePanelLayout = new javax.swing.GroupLayout(ConsultaUsuarioImagePanel);
        ConsultaUsuarioImagePanel.setLayout(ConsultaUsuarioImagePanelLayout);
        ConsultaUsuarioImagePanelLayout.setHorizontalGroup(
            ConsultaUsuarioImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaUsuarioImagePanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(ConsultaUsuarioNoImgLabel)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        ConsultaUsuarioImagePanelLayout.setVerticalGroup(
            ConsultaUsuarioImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaUsuarioImagePanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(ConsultaUsuarioNoImgLabel)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        ConsultaUsuarioBuscarButton.setText("Buscar");
        ConsultaUsuarioBuscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaUsuarioBuscarButtonActionPerformed(evt);
            }
        });

        ConsultaUsuarioNicknameLabel1.setText("Nickname:");

        ControladorUsuario contU = new ControladorUsuario();
        Set <DataUsuario> clientes = contU.listarClientes();
        for(DataUsuario c : clientes) {
            ConsultaUsuarioListaClientes.setName(c.getNombre());
        }
        ConsultaUsuarioScrollPane.setViewportView(ConsultaUsuarioListaClientes);

        ConsultaUsuarioSelecImagenButton.setText("Seleccionar Imagen");

        javax.swing.GroupLayout ConsultaUsuarioFrameLayout = new javax.swing.GroupLayout(ConsultaUsuarioFrame.getContentPane());
        ConsultaUsuarioFrame.getContentPane().setLayout(ConsultaUsuarioFrameLayout);
        ConsultaUsuarioFrameLayout.setHorizontalGroup(
            ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                .addGroup(ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(ConsultaUsuarioVerInfoLabel))
                        .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(ConsultaUsuarioNicknameLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(ConsultaUsuarioTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(ConsultaUsuarioBuscarButton))
                        .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ConsultaUsuarioEmpresaLabel)
                                .addComponent(ConsultaUsuarioURLLabel)
                                .addComponent(ConsultaUsuarioFechaLabel)
                                .addComponent(ConsultaUsuarioCorreoLabel)
                                .addComponent(ConsultaUsuarioNickLabel)
                                .addComponent(ConsultaUsuarioTipoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ConsultaUsuarioApellidoNombreLabel)
                                .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(ConsultaUsuarioSelecImagenButton)
                                    .addGap(44, 44, 44)
                                    .addComponent(ConsultaUsuarioImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ConsultaUsuarioFrameLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ConsultaUsuarioNicknameLabel)
                        .addGap(49, 49, 49)
                        .addComponent(ConsultaUsuarioScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConsultaUsuarioFrameLayout.setVerticalGroup(
            ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConsultaUsuarioVerInfoLabel)
                .addGroup(ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConsultaUsuarioScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConsultaUsuarioTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConsultaUsuarioBuscarButton)
                            .addComponent(ConsultaUsuarioNicknameLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaUsuarioApellidoNombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaUsuarioTipoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaUsuarioNickLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaUsuarioCorreoLabel)
                        .addGap(7, 7, 7)
                        .addComponent(ConsultaUsuarioFechaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaUsuarioEmpresaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaUsuarioURLLabel)
                        .addGroup(ConsultaUsuarioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConsultaUsuarioImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(ConsultaUsuarioSelecImagenButton))))
                    .addGroup(ConsultaUsuarioFrameLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(ConsultaUsuarioNicknameLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCentral.add(ConsultaUsuarioFrame, "card3");

        RegistrarCategoriaFrame.setVisible(true);

        RegCategoriaLabel.setText("Registrar Categoria");

        RegCategoriaNomCategoriaLabel.setText("Nombre");

        RegCategoriaCategoriaPadreLabel.setText("Categoria padre");

        RegCategoriaSinPadreRadioButton.setSelected(true);
        RegCategoriaSinPadreRadioButton.setText("Sin padre");
        RegCategoriaSinPadreRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegCategoriaSinPadreRadioButtonActionPerformed(evt);
            }
        });

        RegCategoriaConPadreRadioButton.setText("Con padre");
        RegCategoriaConPadreRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegCategoriaConPadreRadioButtonActionPerformed(evt);
            }
        });

        RegCategoriaSelecCategoriaPadreLabel.setText("Selecciona la categoria padre");

        RegCategoriaListarCategoriasScrollPane.setViewportView(RegCategoriaListarCategoriasTree);

        RegCategoriaAceptarButton.setText("Aceptar");

        RegCategoriaCancelarButton.setText("Cancelar");

        javax.swing.GroupLayout RegistrarCategoriaFrameLayout = new javax.swing.GroupLayout(RegistrarCategoriaFrame.getContentPane());
        RegistrarCategoriaFrame.getContentPane().setLayout(RegistrarCategoriaFrameLayout);
        RegistrarCategoriaFrameLayout.setHorizontalGroup(
            RegistrarCategoriaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarCategoriaFrameLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(RegistrarCategoriaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarCategoriaFrameLayout.createSequentialGroup()
                        .addComponent(RegCategoriaNomCategoriaLabel)
                        .addGroup(RegistrarCategoriaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrarCategoriaFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(RegCategoriaLabel)
                                .addGap(158, 158, 158))
                            .addGroup(RegistrarCategoriaFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(RegistrarCategoriaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RegCategoriaConPadreRadioButton)
                                    .addComponent(RegCategoriaNombreCategoriaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(RegistrarCategoriaFrameLayout.createSequentialGroup()
                        .addGroup(RegistrarCategoriaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrarCategoriaFrameLayout.createSequentialGroup()
                                .addComponent(RegCategoriaSelecCategoriaPadreLabel)
                                .addGap(38, 38, 38)
                                .addComponent(RegCategoriaListarCategoriasScrollPane))
                            .addGroup(RegistrarCategoriaFrameLayout.createSequentialGroup()
                                .addGroup(RegistrarCategoriaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RegCategoriaAceptarButton)
                                    .addGroup(RegistrarCategoriaFrameLayout.createSequentialGroup()
                                        .addComponent(RegCategoriaCategoriaPadreLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(RegCategoriaSinPadreRadioButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RegCategoriaCancelarButton)
                                .addGap(14, 14, 14)))
                        .addGap(34, 34, 34))))
        );
        RegistrarCategoriaFrameLayout.setVerticalGroup(
            RegistrarCategoriaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarCategoriaFrameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(RegCategoriaLabel)
                .addGap(39, 39, 39)
                .addGroup(RegistrarCategoriaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegCategoriaNomCategoriaLabel)
                    .addComponent(RegCategoriaNombreCategoriaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(RegistrarCategoriaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegCategoriaCategoriaPadreLabel)
                    .addComponent(RegCategoriaSinPadreRadioButton)
                    .addComponent(RegCategoriaConPadreRadioButton))
                .addGap(18, 18, 18)
                .addGroup(RegistrarCategoriaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegCategoriaSelecCategoriaPadreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegCategoriaListarCategoriasScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(RegistrarCategoriaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegCategoriaAceptarButton)
                    .addComponent(RegCategoriaCancelarButton))
                .addGap(36, 36, 36))
        );

        PanelCentral.add(RegistrarCategoriaFrame, "card4");

        RegistrarServicioFrame.setVisible(true);

        RegistrarServicioLabel.setText("Registrar Servicio");

        RegistrarServicioNomServicioLabel.setText("Nombre del servicio");

        RegistrarServicioNomServicioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarServicioNomServicioTextFieldActionPerformed(evt);
            }
        });

        RegistrarServicioDescripcionLabel.setText("Descripción");

        RegistrarServicioSelecImagenesButton.setText("Seleccionar Imágenes");

        RegistrarServicioMax3ImagLabel.setText("(Máximo 3 imágenes)");

        RegistrarServcioPrecioLabel.setText("Precio ($U)");

        RegistrarServicioCiudadOrigenLabel.setText("Ciudad de origen");

        RegistrarServicioCiudadDestinoLabel.setText("Ciudad de destino (opcional)");

        RegistrarServicioConjCategoriasLabel.setText("Conjunto de categorías");

        jScrollPane1.setViewportView(RegistrarServicioCategoriasList);

        RegistrarServicioProveedorLabel.setText("Proveedor");

        RegistrarServicioAceptarButton.setText("Aceptar");

        RegistrarServicioCancelarButton.setText("Cancelar");

        RegistrarServicioProveedorComboBox.setToolTipText("");

        RegistrarServicioCiudadDestinoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Sin ciudad de destino>" }));

        javax.swing.GroupLayout RegistrarServicioFrameLayout = new javax.swing.GroupLayout(RegistrarServicioFrame.getContentPane());
        RegistrarServicioFrame.getContentPane().setLayout(RegistrarServicioFrameLayout);
        RegistrarServicioFrameLayout.setHorizontalGroup(
            RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrarServicioFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegistrarServicioLabel)
                .addGap(160, 160, 160))
            .addGroup(RegistrarServicioFrameLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarServicioFrameLayout.createSequentialGroup()
                        .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrarServicioFrameLayout.createSequentialGroup()
                                .addComponent(RegistrarServcioPrecioLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RegistrarServicioPrecioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrarServicioFrameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(RegistrarServicioAceptarButton)
                                .addGap(11, 11, 11)))
                        .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrarServicioFrameLayout.createSequentialGroup()
                                .addComponent(RegistrarServicioMax3ImagLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(RegistrarServicioFrameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RegistrarServicioCancelarButton)
                                    .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(RegistrarServicioNomServicioTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                        .addComponent(RegistrarServicioTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(RegistrarServicioFrameLayout.createSequentialGroup()
                        .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegistrarServicioNomServicioLabel)
                            .addComponent(RegistrarServicioDescripcionLabel)
                            .addComponent(RegistrarServicioSelecImagenesButton)
                            .addGroup(RegistrarServicioFrameLayout.createSequentialGroup()
                                .addComponent(RegistrarServicioProveedorLabel)
                                .addGap(27, 27, 27)
                                .addComponent(RegistrarServicioProveedorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistrarServicioFrameLayout.createSequentialGroup()
                                .addComponent(RegistrarServicioCiudadDestinoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RegistrarServicioCiudadDestinoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistrarServicioFrameLayout.createSequentialGroup()
                                .addComponent(RegistrarServicioConjCategoriasLabel)
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistrarServicioFrameLayout.createSequentialGroup()
                                .addComponent(RegistrarServicioCiudadOrigenLabel)
                                .addGap(26, 26, 26)
                                .addComponent(RegistrarServicioCiudadOrigenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 148, Short.MAX_VALUE))))
        );
        RegistrarServicioFrameLayout.setVerticalGroup(
            RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrarServicioFrameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(RegistrarServicioLabel)
                .addGap(18, 18, 18)
                .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarServicioNomServicioLabel)
                    .addComponent(RegistrarServicioNomServicioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarServicioDescripcionLabel)
                    .addComponent(RegistrarServicioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarServicioSelecImagenesButton)
                    .addComponent(RegistrarServicioMax3ImagLabel))
                .addGap(18, 18, 18)
                .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarServcioPrecioLabel)
                    .addComponent(RegistrarServicioPrecioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarServicioCiudadOrigenLabel)
                    .addComponent(RegistrarServicioCiudadOrigenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarServicioCiudadDestinoLabel)
                    .addComponent(RegistrarServicioCiudadDestinoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistrarServicioConjCategoriasLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarServicioProveedorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrarServicioProveedorLabel))
                .addGap(34, 34, 34)
                .addGroup(RegistrarServicioFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarServicioCancelarButton)
                    .addComponent(RegistrarServicioAceptarButton))
                .addGap(32, 32, 32))
        );

        PanelCentral.add(RegistrarServicioFrame, "card5");

        MenuInicio.setText("Inicio");
        BarraMenu.add(MenuInicio);

        MenuRegistros.setText("Registros");

        MenuRegistrarUsuario.setText("Registrar Usuario");
        MenuRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarUsuarioActionPerformed(evt);
            }
        });
        MenuRegistros.add(MenuRegistrarUsuario);

        MenuRegistrarCategoria.setText("Registrar Categoria");
        MenuRegistrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarCategoriaActionPerformed(evt);
            }
        });
        MenuRegistros.add(MenuRegistrarCategoria);

        MenuRegistrarServicio.setText("Registrar Servicio");
        MenuRegistrarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarServicioActionPerformed(evt);
            }
        });
        MenuRegistros.add(MenuRegistrarServicio);

        BarraMenu.add(MenuRegistros);

        MenuConsultas.setText("Consultas");

        infoCliente.setText("Ver Informacion de Cliente");
        infoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoClienteActionPerformed(evt);
            }
        });
        MenuConsultas.add(infoCliente);

        BarraMenu.add(MenuConsultas);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarUsuarioActionPerformed

	RegUsuarioAnioComboBox.removeAllItems();
	for (int i = 2015; i > 1900; i--) //genera los años
	    RegUsuarioAnioComboBox.addItem(i);
	ClienteOProveedor.add(RegUsuarioClienteRadioButton);
	ClienteOProveedor.add(RegUsuarioProveedorRadioButton);
	RegUsuarioNombreEmpresaLabel.setVisible(false);
	RegUsuarioURLLabel.setVisible(false);
	RegUsuarioErrorLabel.setVisible(false);
	RegUsuarioNombreEmpresaTextField.setVisible(false);
	RegUsuarioURLTextField.setVisible(false);
	PanelCentral.removeAll();
	PanelCentral.add(RegistrarUsuarioFrame);
	PanelCentral.repaint();
	PanelCentral.revalidate();
	//Muestra el frame de registrar usario en el panel central
    }//GEN-LAST:event_MenuRegistrarUsuarioActionPerformed

    private void RegUsuarioSeleccionarImagenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegUsuarioSeleccionarImagenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegUsuarioSeleccionarImagenButtonActionPerformed

    private void RegUsuarioDiaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegUsuarioDiaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegUsuarioDiaComboBoxActionPerformed

    private void RegUsuarioClienteRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegUsuarioClienteRadioButtonActionPerformed
        RegUsuarioNombreEmpresaLabel.setVisible(false);
	RegUsuarioURLLabel.setVisible(false);
	RegUsuarioNombreEmpresaTextField.setVisible(false);
	RegUsuarioURLTextField.setVisible(false);
    }//GEN-LAST:event_RegUsuarioClienteRadioButtonActionPerformed

    private void RegUsuarioProveedorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegUsuarioProveedorRadioButtonActionPerformed
        RegUsuarioNombreEmpresaLabel.setVisible(true);
	RegUsuarioURLLabel.setVisible(true);
	RegUsuarioNombreEmpresaTextField.setVisible(true);
	RegUsuarioURLTextField.setVisible(true);
    }//GEN-LAST:event_RegUsuarioProveedorRadioButtonActionPerformed

    private void RegUsuarioCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegUsuarioCancelarActionPerformed
        this.RegUsuarioCancelar.doClick();
    }//GEN-LAST:event_RegUsuarioCancelarActionPerformed

    private void ConsultaUsuarioTextFieldLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaUsuarioTextFieldLabelActionPerformed
	ConsultaUsuarioBuscarButton.doClick();
    }//GEN-LAST:event_ConsultaUsuarioTextFieldLabelActionPerformed

    private void infoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoClienteActionPerformed
        ConsultaUsuarioApellidoNombreLabel.setVisible(false);
	ConsultaUsuarioTipoLabel.setVisible(false);
	ConsultaUsuarioNickLabel.setVisible(false);
	ConsultaUsuarioCorreoLabel.setVisible(false);
	ConsultaUsuarioFechaLabel.setVisible(false);
	ConsultaUsuarioEmpresaLabel.setVisible(false);
	ConsultaUsuarioURLLabel.setVisible(false);
	ConsultaUsuarioImagePanel.setVisible(false);
	ConsultaUsuarioNoImgLabel.setVisible(false);
	PanelCentral.removeAll();
	PanelCentral.add(ConsultaUsuarioFrame);
	PanelCentral.repaint();
	PanelCentral.revalidate();
    }//GEN-LAST:event_infoClienteActionPerformed

    private void RegUsuarioAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegUsuarioAceptarActionPerformed
        try
	{
	    ControladorUsuario ctrlUsr = new ControladorUsuario();
	    Calendar cal = Calendar.getInstance();
	    cal.set(Calendar.YEAR, (Integer)(RegUsuarioAnioComboBox.getSelectedItem()));
	    cal.set(Calendar.MONTH, (Integer)(RegUsuarioMesComboBox.getSelectedItem()));
	    cal.set(Calendar.DAY_OF_MONTH, (Integer)(RegUsuarioDiaComboBox.getSelectedItem()));
	    Date d = cal.getTime();
	    if(RegUsuarioClienteRadioButton.isSelected())
	    {
                ctrlUsr.altaCliente(RegUsuarioNombreTextField.getText(), RegUsuarioApellidoTextField.getText(), RegUsuarioNicknameTextField.getText() , 
                        RegUsuarioCorreoTextField.getText(), d);
                
	    }
            this.RegistrarUsuarioFrame.setClosed(true);
            
	}catch(Exception ex)
	{
	    //Muestra el error
	}
    }//GEN-LAST:event_RegUsuarioAceptarActionPerformed

    private void ConsultaUsuarioBuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaUsuarioBuscarButtonActionPerformed
        
    }//GEN-LAST:event_ConsultaUsuarioBuscarButtonActionPerformed

    private void MenuRegistrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarCategoriaActionPerformed
        
        ConPadreOSinPadre.add(RegCategoriaSinPadreRadioButton);
        ConPadreOSinPadre.add(RegCategoriaConPadreRadioButton);
        
        RegCategoriaSelecCategoriaPadreLabel.setVisible(false);
        RegCategoriaListarCategoriasScrollPane.setVisible(false);
        PanelCentral.add(RegistrarCategoriaFrame);
	PanelCentral.repaint();
	PanelCentral.revalidate();

    }//GEN-LAST:event_MenuRegistrarCategoriaActionPerformed

    private void RegCategoriaConPadreRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegCategoriaConPadreRadioButtonActionPerformed
        RegCategoriaSelecCategoriaPadreLabel.setVisible(true);
        RegCategoriaListarCategoriasScrollPane.setVisible(true);
    }//GEN-LAST:event_RegCategoriaConPadreRadioButtonActionPerformed

    private void RegCategoriaSinPadreRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegCategoriaSinPadreRadioButtonActionPerformed
        RegCategoriaSelecCategoriaPadreLabel.setVisible(false);
        RegCategoriaListarCategoriasScrollPane.setVisible(false);
    }//GEN-LAST:event_RegCategoriaSinPadreRadioButtonActionPerformed

    private void RegistrarServicioNomServicioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarServicioNomServicioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarServicioNomServicioTextFieldActionPerformed

    private void MenuRegistrarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarServicioActionPerformed
        PanelCentral.add(RegistrarServicioFrame);
	PanelCentral.repaint();
	PanelCentral.revalidate();
    }//GEN-LAST:event_MenuRegistrarServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	}
	catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
        //</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Interfaz().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.ButtonGroup ClienteOProveedor;
    private javax.swing.ButtonGroup ConPadreOSinPadre;
    private javax.swing.JLabel ConsultaUsuarioApellidoNombreLabel;
    private javax.swing.JButton ConsultaUsuarioBuscarButton;
    private javax.swing.JLabel ConsultaUsuarioCorreoLabel;
    private javax.swing.JLabel ConsultaUsuarioEmpresaLabel;
    private javax.swing.JLabel ConsultaUsuarioFechaLabel;
    private javax.swing.JInternalFrame ConsultaUsuarioFrame;
    private javax.swing.JPanel ConsultaUsuarioImagePanel;
    private javax.swing.JList ConsultaUsuarioListaClientes;
    private javax.swing.JLabel ConsultaUsuarioNickLabel;
    private javax.swing.JLabel ConsultaUsuarioNicknameLabel;
    private javax.swing.JLabel ConsultaUsuarioNicknameLabel1;
    private javax.swing.JLabel ConsultaUsuarioNoImgLabel;
    private javax.swing.JScrollPane ConsultaUsuarioScrollPane;
    private javax.swing.JButton ConsultaUsuarioSelecImagenButton;
    private javax.swing.JTextField ConsultaUsuarioTextFieldLabel;
    private javax.swing.JLabel ConsultaUsuarioTipoLabel;
    private javax.swing.JLabel ConsultaUsuarioURLLabel;
    private javax.swing.JLabel ConsultaUsuarioVerInfoLabel;
    private javax.swing.JMenu MenuConsultas;
    private javax.swing.JMenu MenuInicio;
    private javax.swing.JMenuItem MenuRegistrarCategoria;
    private javax.swing.JMenuItem MenuRegistrarServicio;
    private javax.swing.JMenuItem MenuRegistrarUsuario;
    private javax.swing.JMenu MenuRegistros;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JButton RegCategoriaAceptarButton;
    private javax.swing.JButton RegCategoriaCancelarButton;
    private javax.swing.JLabel RegCategoriaCategoriaPadreLabel;
    private javax.swing.JRadioButton RegCategoriaConPadreRadioButton;
    private javax.swing.JLabel RegCategoriaLabel;
    private javax.swing.JScrollPane RegCategoriaListarCategoriasScrollPane;
    private javax.swing.JTree RegCategoriaListarCategoriasTree;
    private javax.swing.JLabel RegCategoriaNomCategoriaLabel;
    private javax.swing.JTextField RegCategoriaNombreCategoriaTextField;
    private javax.swing.JLabel RegCategoriaSelecCategoriaPadreLabel;
    private javax.swing.JRadioButton RegCategoriaSinPadreRadioButton;
    private javax.swing.JButton RegUsuarioAceptar;
    private javax.swing.JComboBox<Integer> RegUsuarioAnioComboBox;
    private javax.swing.JLabel RegUsuarioApellidoLabel;
    private javax.swing.JTextField RegUsuarioApellidoTextField;
    private javax.swing.JButton RegUsuarioCancelar;
    private javax.swing.JRadioButton RegUsuarioClienteRadioButton;
    private javax.swing.JLabel RegUsuarioCorreoLabel;
    private javax.swing.JTextField RegUsuarioCorreoTextField;
    private javax.swing.JComboBox<Integer> RegUsuarioDiaComboBox;
    private javax.swing.JLabel RegUsuarioErrorLabel;
    private javax.swing.JLabel RegUsuarioFechaLabel;
    private javax.swing.JLabel RegUsuarioLabel;
    private javax.swing.JComboBox<Integer> RegUsuarioMesComboBox;
    private javax.swing.JLabel RegUsuarioNicknameLabel;
    private javax.swing.JTextField RegUsuarioNicknameTextField;
    private javax.swing.JLabel RegUsuarioNombreEmpresaLabel;
    private javax.swing.JTextField RegUsuarioNombreEmpresaTextField;
    private javax.swing.JLabel RegUsuarioNombreLabel;
    private javax.swing.JTextField RegUsuarioNombreTextField;
    private javax.swing.JRadioButton RegUsuarioProveedorRadioButton;
    private javax.swing.JButton RegUsuarioSeleccionarImagenButton;
    private javax.swing.JLabel RegUsuarioURLLabel;
    private javax.swing.JTextField RegUsuarioURLTextField;
    private javax.swing.JInternalFrame RegistrarCategoriaFrame;
    private javax.swing.JLabel RegistrarServcioPrecioLabel;
    private javax.swing.JButton RegistrarServicioAceptarButton;
    private javax.swing.JButton RegistrarServicioCancelarButton;
    private javax.swing.JList RegistrarServicioCategoriasList;
    private javax.swing.JComboBox RegistrarServicioCiudadDestinoComboBox;
    private javax.swing.JLabel RegistrarServicioCiudadDestinoLabel;
    private javax.swing.JComboBox RegistrarServicioCiudadOrigenComboBox;
    private javax.swing.JLabel RegistrarServicioCiudadOrigenLabel;
    private javax.swing.JLabel RegistrarServicioConjCategoriasLabel;
    private javax.swing.JLabel RegistrarServicioDescripcionLabel;
    private javax.swing.JInternalFrame RegistrarServicioFrame;
    private javax.swing.JLabel RegistrarServicioLabel;
    private javax.swing.JLabel RegistrarServicioMax3ImagLabel;
    private javax.swing.JLabel RegistrarServicioNomServicioLabel;
    private javax.swing.JTextField RegistrarServicioNomServicioTextField;
    private javax.swing.JTextField RegistrarServicioPrecioTextField;
    private javax.swing.JComboBox RegistrarServicioProveedorComboBox;
    private javax.swing.JLabel RegistrarServicioProveedorLabel;
    private javax.swing.JButton RegistrarServicioSelecImagenesButton;
    private javax.swing.JTextField RegistrarServicioTextField;
    private javax.swing.JInternalFrame RegistrarUsuarioFrame;
    private javax.swing.JMenuItem infoCliente;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
